### ISSUE TITLE
TdObjects have only from json constructor

### ISSUE THREAD

**Issue by rafalbednarczuk** [periodicaidan/dart_tdlib#1]
Why do classes in functions.dart file have standard constructor and these in objects.dart have constructor which is created from json?
It is more convenient to have this standard constructor

**Comment by periodicaidan** [comment]
My original reasoning was that `TdObject`s are usually constructed from messages coming from the `JsonClient`, whereas `TdFunction`s are usually constructed with data you the programmer define, so it seemed more convenient just to be able to pass the JSON object to the constructors of `TdObject`s, and pass individual parameters to the constructors of `TdFunction`s.

However, now that you bring it up, that is kind of inconsistent and unintuitive. I think I'll change it so the default constructor accepts keyword-arguments and then give it a `fromJson` constructor. And give `TdFunction`s a `fromJson` constructor as well.
